dateModified: 1722373456
email:
  fromEmail: marrerkevin@gmail.com
  fromName: imgonnakms
  transportType: craft\mail\transportadapters\Sendmail
fs:
  nmixxSigma:
    hasUrls: true
    name: 'Nmixx Sigma'
    settings:
      path: '@webroot/images/uploads/background'
    type: craft\fs\Local
    url: '@web/images/uploads/background'
meta:
  __names__:
    1d0783a1-76ec-44f5-a957-094f045642a5: 'Spotify Search' # Spotify Search
    9e37425c-7e14-42b0-b193-085f0f2b102e: imgonnakms # imgonnakms
    34d5ce65-aa30-40a8-9da9-fe1e1af4e067: 'Sigma Backgrounds' # Sigma Backgrounds
    098f0772-4c1b-4486-bf87-ec9678a5249b: imgonnakms # imgonnakms
    16801b40-2fe0-4ffa-b3cc-232644f96ea0: 'Sigma Backgrounds' # Sigma Backgrounds
    a74db08b-5408-4b74-aa6c-9b94d914c1fe: home # home
    c1bfa06f-237d-4c90-98e3-8532fe307960: 'Spotify Search' # Spotify Search
    c6530af9-81e8-4141-8733-fb8719e61358: intro # intro
    f37086e7-debc-477c-9e07-24df2742b1c1: home # home
system:
  edition: solo
  live: true
  name: imgonnakms
  schemaVersion: 5.0.0.21
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
